[phases.setup]
nixPkgs = ["php84", "composer", "nodejs"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "php artisan route:clear"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"